global:
  scrape_interval:     1m
  evaluation_interval: 1m
  
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5m 
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'ev_charger'
    static_configs:
         - targets: 
           - "ev_charger_a:8000"
           - "ev_charger_b:8000"
           - "ev_charger_c:8000" # this one is down for illustration

