version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  back-tier:

services:
  nginx:
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    volumes:
        - ./nginx/ssl:/etc/nginx/ssl
        - ./nginx/service.conf:/etc/nginx/service.conf
    ports:
        - "80:80"
        - "443:443"
    environment:
        - TZ=America/Chicago
        - LETSENCRYPT=true
        - LE_EMAIL=mail@aparcar.org
        - LE_FQDN=hacc.aparcar.org
    networks:
      - back-tier

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 8000
    networks:
      - back-tier

  ev_charger_1:
    build:
      context: .
      dockerfile: Dockerfile.ev_charger_simulator
    ports:
    - 8000
    environment:
        STATION: "Hawaii Kai 7-Eleven"
        ADDRESS: "515 Pepeekeo St Honolulu, HI 96825"
        LOCATION: "21.29730/-157.70932"
        START_MONTH: 1
    networks:
      - back-tier

  ev_charger_2:
    build:
      context: .
      dockerfile: Dockerfile.ev_charger_simulator
    ports:
    - 8000
    environment:
        STATION: "Hawaiian Electric Ward Office"
        ADDRESS: "820 Ward Avenue Honolulu, HI 96814"
        LOCATION: "21.30569/-157.84872"
        START_MONTH: 2
    networks:
      - back-tier

  ev_charger_3:
    build:
      context: .
      dockerfile: Dockerfile.ev_charger_simulator
    ports:
    - 8000
    environment:
        STATION: "Iwilei Costco Parking Lot"
        ADDRESS: "801 Dillingham Building Honolulu, HI 96817"
        LOCATION: "21.31866/-157.86713"
        START_MONTH: 3
    networks:
      - back-tier

  ev_charger_4:
    build:
      context: .
      dockerfile: Dockerfile.ev_charger_simulator
    ports:
    - 8000
    environment:
        STATION: "Times Square Shopping Center"
        ADDRESS: "98-1268 Kaahumanu St Pearl City, HI 96782"
        LOCATION: "21.38714/-157.95443"
        START_MONTH: 4
    networks:
      - back-tier

  ev_charger_5:
    build:
      context: .
      dockerfile: Dockerfile.ev_charger_simulator
    ports:
    - 8000
    environment:
        STATION: "Koolau Center"
        ADDRESS: "47-388 Hui Iwa Street Kaneohe, HI 96744"
        LOCATION: "21.38714/-157.95443"
        START_MONTH: 5
    networks:
      - back-tier

  redis:
    image: redis:alpine
    ports:
    - 6379
    networks:
      - back-tier

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090
    restart: always
    networks:
      - back-tier

  grafana:
    image: grafana/grafana:latest
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
      - ./grafana/admin.password
    restart: always
    networks:
      - back-tier
