version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}
    caddy_data: {}

networks:
  front-tier:
  back-tier:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    networks:
      - back-tier
        #  caddy:
        #    image: abiosoft/caddy
        #    volumes:
        #      - ./Caddyfile:/etc/Caddyfile"
        #      - caddy_data:/root/.caddy
        #    ports:
        #      - "80:80"
        #      - "433:433"
        #    networks:
        #      - back-tier
        #      - front-tier
  ev_charger:
    build:
      context: .
      dockerfile: Dockerfile.ev_charger_simulator
    ports:
    - "8000"
    networks:
      - back-tier
    environment:
      STATION: "A"

  redis:
    image: redis:alpine
    ports:
    - "6379"
    networks:
      - back-tier

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana:latest
    user: "104"
    depends_on:
      - prometheus
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/

    env_file:
      - ./grafana/config.monitoring
      - ./grafana/admin.password
    networks:
      - back-tier
    restart: always
