version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  ev_charger_a:
    build: .
    container_name: ev_charger_a
    ports:
    - "8000"
    networks:
      - back-tier
    environment:
      STATION: "A"

  ev_charger_b:
    build: .
    container_name: ev_charger_b
    ports:
    - "8000"
    networks:
      - back-tier
    environment:
      STATION: "B"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana:latest
    user: "104"
    depends_on:
      - prometheus
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
      - ./grafana/admin.password
    networks:
      - back-tier
      - front-tier
    restart: always
