global:
  scrape_interval:     1m
  evaluation_interval: 1m
  
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5m 
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'lookups'
    scrape_interval: 1m 
    metrics_path: "/lookups"
    static_configs:
         - targets: ['app:8000']

  - job_name: 'ev_charger'
    dns_sd_configs:
    - names:
      - 'ev_charger'
      type: 'A'
      port: 8000

