global:
  scrape_interval:     1m
  evaluation_interval: 1m
  
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5m 
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'lookups'
    scrape_interval: 1m 
    metrics_path: "/lookups"
    static_configs:
         - targets: ['app:8000']

  - job_name: 'ev_charger'
    static_configs:
        - targets: ['ev_charger_1:8000']
          labels:
            station: "Hawaii Kai 7-Eleven"
        - targets: ['ev_charger_2:8000']
          labels:
            station: "Hawaiian Electric Ward Office"
        - targets: ['ev_charger_3:8000']
          labels:
            station: "Iwilei Costco Parking Lot"
        - targets: ['ev_charger_4:8000']
          labels:
            station: "Times Square Shopping Center"
        - targets: ['ev_charger_5:8000']
          labels:
            station: "Koolau Center"
