{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current total Watt",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(evc_kwh)" }
   ]
  },
  {
   "title": "Lookups",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(lookup)" }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "first",
   "targets": [
    { "expr": "count(evc_session_id!=0)" }
   ]
  },
  {
   "title": "Payment Methods",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum_over_time(evc_payment_method{evc_payment_method!=\"\"}[24h])) by (evc_payment_method) / ignoring(evc_payment_method) group_left sum (sum_over_time(evc_payment_method[24h]))",
     "legendFormat": "{{ evc_payment_method }}"
    }
   ]
  },
  {
   "title": "Session Initiated By",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum_over_time(evc_session_initiated_by{evc_session_initiated_by!=\"\"}[24h])) by (evc_session_initiated_by) / ignoring(evc_session_initiated_by) group_left sum (sum_over_time(evc_session_initiated_by[24h]))",
     "legendFormat": "{{ evc_session_initiated_by }}"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "kwh",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "evc_kwh", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Station Status",
   "type": "table",
   "gridPos": { "h": 18, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "expr": "up{job=\"ev_charger\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 11 },
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(lookup) by (geohash) or evc_meta_info"
    }
   ]
  }
 ]
}