{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "current kwh",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(kwh)" }
   ]
  },
  {
   "title": "Payment Methods",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(payment_method{payment_method!=\"\"}) by (payment_method)",
     "legendFormat": "{{ payment_method }}"
    }
   ]
  },
  {
   "title": "Session Initiated By",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(session_initiated_by{session_initiated_by!=\"\"}) by (session_initiated_by)",
     "legendFormat": "{{ session_initiated_by }}"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "kwh",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kwh", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Station Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "up{job=\"ev_charger\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}